/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryGetCategoriesByIdFieldsItem } from "./categoryGetCategoriesByIdFieldsItem";
import type { CategoryGetCategoriesByIdPopulateAnyOfItem } from "./categoryGetCategoriesByIdPopulateAnyOfItem";
import type { CategoryGetCategoriesByIdSortAnyOfItem } from "./categoryGetCategoriesByIdSortAnyOfItem";
import type { CategoryGetCategoriesByIdSortAnyOfTwo } from "./categoryGetCategoriesByIdSortAnyOfTwo";
import type { CategoryGetCategoriesByIdSortAnyOfThreeItem } from "./categoryGetCategoriesByIdSortAnyOfThreeItem";

export type CategoryGetCategoriesByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly CategoryGetCategoriesByIdFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | CategoryGetCategoriesByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Sort the result
   */
  sort?:
    | "name"
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | CategoryGetCategoriesByIdSortAnyOfItem[]
    | CategoryGetCategoriesByIdSortAnyOfTwo
    | CategoryGetCategoriesByIdSortAnyOfThreeItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
