/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryGetCategoriesFieldsItem } from "./categoryGetCategoriesFieldsItem";
import type { CategoryGetCategoriesPaginationAllOf } from "./categoryGetCategoriesPaginationAllOf";
import type { CategoryGetCategoriesPaginationAllOfTwo } from "./categoryGetCategoriesPaginationAllOfTwo";
import type { CategoryGetCategoriesSortAnyOfItem } from "./categoryGetCategoriesSortAnyOfItem";
import type { CategoryGetCategoriesSortAnyOfTwo } from "./categoryGetCategoriesSortAnyOfTwo";
import type { CategoryGetCategoriesSortAnyOfThreeItem } from "./categoryGetCategoriesSortAnyOfThreeItem";
import type { CategoryGetCategoriesPopulateAnyOfItem } from "./categoryGetCategoriesPopulateAnyOfItem";

export type CategoryGetCategoriesParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly CategoryGetCategoriesFieldsItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  _q?: string;
  /**
   * Pagination parameters
   */
  pagination?: CategoryGetCategoriesPaginationAllOf &
    CategoryGetCategoriesPaginationAllOfTwo;
  /**
   * Sort the result
   */
  sort?:
    | "name"
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | CategoryGetCategoriesSortAnyOfItem[]
    | CategoryGetCategoriesSortAnyOfTwo
    | CategoryGetCategoriesSortAnyOfThreeItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | CategoryGetCategoriesPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
