/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type CategoryPutCategoriesByIdBodyData = {
  /** A string field */
  name?: string;
  /** A UID field */
  slug?: string;
  /** A datetime field */
  publishedAt?: string;
  /** A string field */
  locale?: string;
  /**
   * A relational field
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$
   */
  recipe?: string;
};
