/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type CategoryPutCategoriesByIdFieldsItem =
  (typeof CategoryPutCategoriesByIdFieldsItem)[keyof typeof CategoryPutCategoriesByIdFieldsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryPutCategoriesByIdFieldsItem = {
  name: "name",
  slug: "slug",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  publishedAt: "publishedAt",
  locale: "locale",
} as const;
