/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryDeleteCategoriesByIdFieldsItem } from "./categoryDeleteCategoriesByIdFieldsItem";
import type { CategoryDeleteCategoriesByIdPopulateAnyOfItem } from "./categoryDeleteCategoriesByIdPopulateAnyOfItem";

export type CategoryDeleteCategoriesByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly CategoryDeleteCategoriesByIdFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | CategoryDeleteCategoriesByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Select a locale
   */
  locale?: string;
};
