/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryPostCategoriesFieldsItem } from "./categoryPostCategoriesFieldsItem";
import type { CategoryPostCategoriesPopulateAnyOfItem } from "./categoryPostCategoriesPopulateAnyOfItem";

export type CategoryPostCategoriesParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly CategoryPostCategoriesFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | CategoryPostCategoriesPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
