/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryPutCategoriesById200Data } from "./categoryPutCategoriesById200Data";

export type CategoryPutCategoriesById200 = {
  data: CategoryPutCategoriesById200Data;
};
