/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientPostIngredientsFieldsItem } from "./ingredientPostIngredientsFieldsItem";
import type { IngredientPostIngredientsPopulateAnyOfItem } from "./ingredientPostIngredientsPopulateAnyOfItem";

export type IngredientPostIngredientsParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly IngredientPostIngredientsFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | IngredientPostIngredientsPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
