/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientPostIngredients200Data } from "./ingredientPostIngredients200Data";

export type IngredientPostIngredients200 = {
  data: IngredientPostIngredients200Data;
};
