/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientGetIngredientsFieldsItem } from "./ingredientGetIngredientsFieldsItem";
import type { IngredientGetIngredientsPaginationAllOf } from "./ingredientGetIngredientsPaginationAllOf";
import type { IngredientGetIngredientsPaginationAllOfTwo } from "./ingredientGetIngredientsPaginationAllOfTwo";
import type { IngredientGetIngredientsSortAnyOfItem } from "./ingredientGetIngredientsSortAnyOfItem";
import type { IngredientGetIngredientsSortAnyOfTwo } from "./ingredientGetIngredientsSortAnyOfTwo";
import type { IngredientGetIngredientsSortAnyOfThreeItem } from "./ingredientGetIngredientsSortAnyOfThreeItem";
import type { IngredientGetIngredientsPopulateAnyOfItem } from "./ingredientGetIngredientsPopulateAnyOfItem";

export type IngredientGetIngredientsParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly IngredientGetIngredientsFieldsItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  _q?: string;
  /**
   * Pagination parameters
   */
  pagination?: IngredientGetIngredientsPaginationAllOf &
    IngredientGetIngredientsPaginationAllOfTwo;
  /**
   * Sort the result
   */
  sort?:
    | "name"
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | IngredientGetIngredientsSortAnyOfItem[]
    | IngredientGetIngredientsSortAnyOfTwo
    | IngredientGetIngredientsSortAnyOfThreeItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | IngredientGetIngredientsPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
