/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientDeleteIngredientsByIdFieldsItem } from "./ingredientDeleteIngredientsByIdFieldsItem";
import type { IngredientDeleteIngredientsByIdPopulateAnyOfItem } from "./ingredientDeleteIngredientsByIdPopulateAnyOfItem";

export type IngredientDeleteIngredientsByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly IngredientDeleteIngredientsByIdFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | IngredientDeleteIngredientsByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Select a locale
   */
  locale?: string;
};
