/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientGetIngredientsByIdFieldsItem } from "./ingredientGetIngredientsByIdFieldsItem";
import type { IngredientGetIngredientsByIdPopulateAnyOfItem } from "./ingredientGetIngredientsByIdPopulateAnyOfItem";
import type { IngredientGetIngredientsByIdSortAnyOfItem } from "./ingredientGetIngredientsByIdSortAnyOfItem";
import type { IngredientGetIngredientsByIdSortAnyOfTwo } from "./ingredientGetIngredientsByIdSortAnyOfTwo";
import type { IngredientGetIngredientsByIdSortAnyOfThreeItem } from "./ingredientGetIngredientsByIdSortAnyOfThreeItem";

export type IngredientGetIngredientsByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly IngredientGetIngredientsByIdFieldsItem[];
  populate?:
    | "*"
    | "recipe"
    | "localizations"
    | IngredientGetIngredientsByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Sort the result
   */
  sort?:
    | "name"
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | IngredientGetIngredientsByIdSortAnyOfItem[]
    | IngredientGetIngredientsByIdSortAnyOfTwo
    | IngredientGetIngredientsByIdSortAnyOfThreeItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
