/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientDeleteIngredientsById200Data } from "./ingredientDeleteIngredientsById200Data";

export type IngredientDeleteIngredientsById200 = {
  data: IngredientDeleteIngredientsById200Data;
};
