/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type IngredientPutIngredientsByIdPopulateAnyOfItem =
  (typeof IngredientPutIngredientsByIdPopulateAnyOfItem)[keyof typeof IngredientPutIngredientsByIdPopulateAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngredientPutIngredientsByIdPopulateAnyOfItem = {
  recipe: "recipe",
  localizations: "localizations",
} as const;
