/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientPutIngredientsById200Data } from "./ingredientPutIngredientsById200Data";

export type IngredientPutIngredientsById200 = {
  data: IngredientPutIngredientsById200Data;
};
