/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type IngredientPostIngredientsPopulateAnyOfItem =
  (typeof IngredientPostIngredientsPopulateAnyOfItem)[keyof typeof IngredientPostIngredientsPopulateAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngredientPostIngredientsPopulateAnyOfItem = {
  recipe: "recipe",
  localizations: "localizations",
} as const;
