/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { IngredientGetIngredients200DataItem } from "./ingredientGetIngredients200DataItem";

export type IngredientGetIngredients200 = {
  data: IngredientGetIngredients200DataItem[];
};
