/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PhoneNumverGetPhoneNumversByIdFieldsItem } from "./phoneNumverGetPhoneNumversByIdFieldsItem";
import type { PhoneNumverGetPhoneNumversByIdPopulateAnyOfItem } from "./phoneNumverGetPhoneNumversByIdPopulateAnyOfItem";
import type { PhoneNumverGetPhoneNumversByIdSortAnyOfItem } from "./phoneNumverGetPhoneNumversByIdSortAnyOfItem";
import type { PhoneNumverGetPhoneNumversByIdSortAnyOfTwo } from "./phoneNumverGetPhoneNumversByIdSortAnyOfTwo";
import type { PhoneNumverGetPhoneNumversByIdSortAnyOfThreeItem } from "./phoneNumverGetPhoneNumversByIdSortAnyOfThreeItem";

export type PhoneNumverGetPhoneNumversByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly PhoneNumverGetPhoneNumversByIdFieldsItem[];
  populate?: "*" | "user" | PhoneNumverGetPhoneNumversByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Sort the result
   */
  sort?:
    | "dumb_number"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | PhoneNumverGetPhoneNumversByIdSortAnyOfItem[]
    | PhoneNumverGetPhoneNumversByIdSortAnyOfTwo
    | PhoneNumverGetPhoneNumversByIdSortAnyOfThreeItem[];
};
