/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PhoneNumverGetPhoneNumversFieldsItem } from "./phoneNumverGetPhoneNumversFieldsItem";
import type { PhoneNumverGetPhoneNumversPaginationAllOf } from "./phoneNumverGetPhoneNumversPaginationAllOf";
import type { PhoneNumverGetPhoneNumversPaginationAllOfTwo } from "./phoneNumverGetPhoneNumversPaginationAllOfTwo";
import type { PhoneNumverGetPhoneNumversSortAnyOfItem } from "./phoneNumverGetPhoneNumversSortAnyOfItem";
import type { PhoneNumverGetPhoneNumversSortAnyOfTwo } from "./phoneNumverGetPhoneNumversSortAnyOfTwo";
import type { PhoneNumverGetPhoneNumversSortAnyOfThreeItem } from "./phoneNumverGetPhoneNumversSortAnyOfThreeItem";
import type { PhoneNumverGetPhoneNumversPopulateAnyOfItem } from "./phoneNumverGetPhoneNumversPopulateAnyOfItem";

export type PhoneNumverGetPhoneNumversParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly PhoneNumverGetPhoneNumversFieldsItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  _q?: string;
  /**
   * Pagination parameters
   */
  pagination?: PhoneNumverGetPhoneNumversPaginationAllOf &
    PhoneNumverGetPhoneNumversPaginationAllOfTwo;
  /**
   * Sort the result
   */
  sort?:
    | "dumb_number"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | PhoneNumverGetPhoneNumversSortAnyOfItem[]
    | PhoneNumverGetPhoneNumversSortAnyOfTwo
    | PhoneNumverGetPhoneNumversSortAnyOfThreeItem[];
  populate?: "*" | "user" | PhoneNumverGetPhoneNumversPopulateAnyOfItem[];
};
