/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PluginUsersPermissionsPermissionDocumentId } from "./pluginUsersPermissionsPermissionDocumentId";
import type { PluginUsersPermissionsRoleDocument } from "./pluginUsersPermissionsRoleDocument";

export interface PluginUsersPermissionsPermissionDocument {
  /**
   * The document ID, represented by a UUID
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$
   */
  documentId: string;
  id: PluginUsersPermissionsPermissionDocumentId;
  /** A string field */
  action: string;
  /** A datetime field */
  createdAt?: string;
  /** A datetime field */
  updatedAt?: string;
  /** A datetime field */
  publishedAt: string;
  /** A relational field */
  role?: PluginUsersPermissionsRoleDocument;
}
