/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PluginUsersPermissionsUserDocumentId } from "./pluginUsersPermissionsUserDocumentId";
import type { PluginUsersPermissionsUserDocumentConfirmed } from "./pluginUsersPermissionsUserDocumentConfirmed";
import type { PluginUsersPermissionsUserDocumentBlocked } from "./pluginUsersPermissionsUserDocumentBlocked";
import type { PluginUsersPermissionsUserDocumentIsPhoneVerified } from "./pluginUsersPermissionsUserDocumentIsPhoneVerified";
import type { PluginUsersPermissionsRoleDocument } from "./pluginUsersPermissionsRoleDocument";
import type { ApiPhoneNumverPhoneNumverDocument } from "./apiPhoneNumverPhoneNumverDocument";

/**
 * User document with authentication and profile information
 */
export interface PluginUsersPermissionsUserDocument {
  /**
   * Unique document identifier (UUID v4)
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$
   */
  documentId: string;
  id: PluginUsersPermissionsUserDocumentId;
  /** User's unique username for authentication */
  username: string;
  /**
   * User's email address (unique, validated)
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /** A string field */
  provider?: string;
  /** Whether email has been confirmed */
  confirmed: PluginUsersPermissionsUserDocumentConfirmed;
  /** Whether user is blocked from accessing the system */
  blocked: PluginUsersPermissionsUserDocumentBlocked;
  /** Whether phone number has been verified */
  isPhoneVerified: PluginUsersPermissionsUserDocumentIsPhoneVerified;
  /** A datetime field */
  createdAt?: string;
  /** A datetime field */
  updatedAt?: string;
  /** A datetime field */
  publishedAt: string;
  /** A relational field */
  role?: PluginUsersPermissionsRoleDocument;
  /** A relational field */
  phone_numvers?: ApiPhoneNumverPhoneNumverDocument[];
}
