/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PluginUploadFileDocument } from "./pluginUploadFileDocument";
import type { ApiCategoryCategoryDocument } from "./apiCategoryCategoryDocument";
import type { ApiIngredientIngredientDocument } from "./apiIngredientIngredientDocument";
import type { ApiRecipeRecipeDocument } from "./apiRecipeRecipeDocument";

export type RecipeGetRecipes200DataItem = {
  /**
   * The document ID, represented by a UUID
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$
   */
  documentId: string;
  id: number;
  /** A string field */
  title?: string;
  /** A UID field */
  slug?: string;
  /** A string field */
  description?: string;
  /** A blocks field */
  instructions: unknown[];
  /**
   * An integer field
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  preparation_time?: number;
  /**
   * An integer field
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  cook_time?: number;
  /** A boolean field */
  is_featured?: boolean;
  /** A datetime field */
  createdAt?: string;
  /** A datetime field */
  updatedAt?: string;
  /** A datetime field */
  publishedAt: string;
  /** A string field */
  locale?: string;
  /** A media field */
  main_image?: PluginUploadFileDocument;
  /** A relational field */
  categories?: ApiCategoryCategoryDocument[];
  /** A relational field */
  ingredients?: ApiIngredientIngredientDocument[];
  /** A relational field */
  readonly localizations?: readonly ApiRecipeRecipeDocument[];
};
