/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { RecipePutRecipesByIdFieldsItem } from "./recipePutRecipesByIdFieldsItem";
import type { RecipePutRecipesByIdPopulateAnyOfItem } from "./recipePutRecipesByIdPopulateAnyOfItem";

export type RecipePutRecipesByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly RecipePutRecipesByIdFieldsItem[];
  populate?:
    | "*"
    | "main_image"
    | "categories"
    | "ingredients"
    | "localizations"
    | RecipePutRecipesByIdPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
