/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { RecipePostRecipesFieldsItem } from "./recipePostRecipesFieldsItem";
import type { RecipePostRecipesPopulateAnyOfItem } from "./recipePostRecipesPopulateAnyOfItem";

export type RecipePostRecipesParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly RecipePostRecipesFieldsItem[];
  populate?:
    | "*"
    | "main_image"
    | "categories"
    | "ingredients"
    | "localizations"
    | RecipePostRecipesPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
