/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { RecipeGetRecipesByIdFieldsItem } from "./recipeGetRecipesByIdFieldsItem";
import type { RecipeGetRecipesByIdPopulateAnyOfItem } from "./recipeGetRecipesByIdPopulateAnyOfItem";
import type { RecipeGetRecipesByIdSortAnyOfItem } from "./recipeGetRecipesByIdSortAnyOfItem";
import type { RecipeGetRecipesByIdSortAnyOfTwo } from "./recipeGetRecipesByIdSortAnyOfTwo";
import type { RecipeGetRecipesByIdSortAnyOfThreeItem } from "./recipeGetRecipesByIdSortAnyOfThreeItem";

export type RecipeGetRecipesByIdParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly RecipeGetRecipesByIdFieldsItem[];
  populate?:
    | "*"
    | "main_image"
    | "categories"
    | "ingredients"
    | "localizations"
    | RecipeGetRecipesByIdPopulateAnyOfItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  /**
   * Sort the result
   */
  sort?:
    | "title"
    | "slug"
    | "description"
    | "instructions"
    | "preparation_time"
    | "cook_time"
    | "is_featured"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | RecipeGetRecipesByIdSortAnyOfItem[]
    | RecipeGetRecipesByIdSortAnyOfTwo
    | RecipeGetRecipesByIdSortAnyOfThreeItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
