/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { RecipePutRecipesByIdBodyDataIsFeatured } from "./recipePutRecipesByIdBodyDataIsFeatured";

export type RecipePutRecipesByIdBodyData = {
  /** A string field */
  title?: string;
  /** A UID field */
  slug?: string;
  /** A string field */
  description?: string;
  /** A blocks field */
  instructions?: unknown[];
  /**
   * A float field
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  preparation_time?: number;
  /**
   * A float field
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  cook_time?: number;
  /** A boolean field */
  is_featured?: RecipePutRecipesByIdBodyDataIsFeatured;
  /** A datetime field */
  publishedAt?: string;
  /** A string field */
  locale?: string;
  /** A media field */
  main_image?: unknown;
  /** A relational field */
  categories?: string[];
  /** A relational field */
  ingredients?: string[];
};
