/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { RecipeGetRecipesFieldsItem } from "./recipeGetRecipesFieldsItem";
import type { RecipeGetRecipesPaginationAllOf } from "./recipeGetRecipesPaginationAllOf";
import type { RecipeGetRecipesPaginationAllOfTwo } from "./recipeGetRecipesPaginationAllOfTwo";
import type { RecipeGetRecipesSortAnyOfItem } from "./recipeGetRecipesSortAnyOfItem";
import type { RecipeGetRecipesSortAnyOfTwo } from "./recipeGetRecipesSortAnyOfTwo";
import type { RecipeGetRecipesSortAnyOfThreeItem } from "./recipeGetRecipesSortAnyOfThreeItem";
import type { RecipeGetRecipesPopulateAnyOfItem } from "./recipeGetRecipesPopulateAnyOfItem";

export type RecipeGetRecipesParams = {
  /**
   * The fields to return, this doesn't include populatable fields like relations, components, files, or dynamic zones
   */
  fields?: readonly RecipeGetRecipesFieldsItem[];
  /**
   * Filters to apply to the query
   */
  filters?: { [key: string]: unknown };
  _q?: string;
  /**
   * Pagination parameters
   */
  pagination?: RecipeGetRecipesPaginationAllOf &
    RecipeGetRecipesPaginationAllOfTwo;
  /**
   * Sort the result
   */
  sort?:
    | "title"
    | "slug"
    | "description"
    | "instructions"
    | "preparation_time"
    | "cook_time"
    | "is_featured"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "locale"
    | RecipeGetRecipesSortAnyOfItem[]
    | RecipeGetRecipesSortAnyOfTwo
    | RecipeGetRecipesSortAnyOfThreeItem[];
  populate?:
    | "*"
    | "main_image"
    | "categories"
    | "ingredients"
    | "localizations"
    | RecipeGetRecipesPopulateAnyOfItem[];
  /**
   * Select a locale
   */
  locale?: string;
};
