/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

/**
 * A boolean field
 */
export type RecipePutRecipesByIdBodyDataIsFeatured =
  (typeof RecipePutRecipesByIdBodyDataIsFeatured)[keyof typeof RecipePutRecipesByIdBodyDataIsFeatured];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipePutRecipesByIdBodyDataIsFeatured = {
  NUMBER_0: "0",
  NUMBER_1: "1",
  t: "t",
  true: "true",
  f: "f",
  false: "false",
} as const;
