/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type RecipeGetRecipesByIdSortAnyOfItem =
  (typeof RecipeGetRecipesByIdSortAnyOfItem)[keyof typeof RecipeGetRecipesByIdSortAnyOfItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipeGetRecipesByIdSortAnyOfItem = {
  title: "title",
  slug: "slug",
  description: "description",
  instructions: "instructions",
  preparation_time: "preparation_time",
  cook_time: "cook_time",
  is_featured: "is_featured",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  publishedAt: "publishedAt",
  locale: "locale",
} as const;
