/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */

export type UsersPermissionsGetAuthByProviderCallbackParams = {
  /**
   * OAuth access token returned by provider
   */
  access_token?: string;
  /**
   * OAuth authorization code
   */
  code?: string;
  /**
   * OAuth state parameter for CSRF protection
   */
  state?: string;
  /**
   * OAuth error code if authentication failed
   */
  error?: string;
  /**
   * Human-readable error description
   */
  error_description?: string;
};
