/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { PluginUsersPermissionsUserDocument } from "./pluginUsersPermissionsUserDocument";
import type { UsersPermissionsGetUsers200Meta } from "./usersPermissionsGetUsers200Meta";

export type UsersPermissionsGetUsers200 = {
  data?: PluginUsersPermissionsUserDocument[];
  meta?: UsersPermissionsGetUsers200Meta;
};
