/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  ContentTypeBuilderGetComponents200,
  ContentTypeBuilderGetComponentsByUid200,
  ContentTypeBuilderGetContentTypes200,
  ContentTypeBuilderGetContentTypesByUid200,
  ContentTypeBuilderGetContentTypesParams,
} from "../learningStrapiV5.schemas";

import { strapiAuthenticatedClient } from "../../lib/strapi-client";

export const getContentTypeBuilder = () => {
  const contentTypeBuilderGetContentTypes = (
    params: ContentTypeBuilderGetContentTypesParams,
  ) => {
    return strapiAuthenticatedClient<ContentTypeBuilderGetContentTypes200>({
      url: `/content-types`,
      method: "GET",
      params,
    });
  };
  const contentTypeBuilderGetContentTypesByUid = (uid: string) => {
    return strapiAuthenticatedClient<ContentTypeBuilderGetContentTypesByUid200>(
      { url: `/content-types/${uid}`, method: "GET" },
    );
  };
  const contentTypeBuilderGetComponents = () => {
    return strapiAuthenticatedClient<ContentTypeBuilderGetComponents200>({
      url: `/components`,
      method: "GET",
    });
  };
  const contentTypeBuilderGetComponentsByUid = (uid: string) => {
    return strapiAuthenticatedClient<ContentTypeBuilderGetComponentsByUid200>({
      url: `/components/${uid}`,
      method: "GET",
    });
  };
  return {
    contentTypeBuilderGetContentTypes,
    contentTypeBuilderGetContentTypesByUid,
    contentTypeBuilderGetComponents,
    contentTypeBuilderGetComponentsByUid,
  };
};
export type ContentTypeBuilderGetContentTypesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContentTypeBuilder
      >["contentTypeBuilderGetContentTypes"]
    >
  >
>;
export type ContentTypeBuilderGetContentTypesByUidResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContentTypeBuilder
      >["contentTypeBuilderGetContentTypesByUid"]
    >
  >
>;
export type ContentTypeBuilderGetComponentsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContentTypeBuilder
      >["contentTypeBuilderGetComponents"]
    >
  >
>;
export type ContentTypeBuilderGetComponentsByUidResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getContentTypeBuilder
      >["contentTypeBuilderGetComponentsByUid"]
    >
  >
>;
