/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  PhoneNumverDeletePhoneNumversById200,
  PhoneNumverDeletePhoneNumversByIdParams,
  PhoneNumverGetPhoneNumvers200,
  PhoneNumverGetPhoneNumversById200,
  PhoneNumverGetPhoneNumversByIdParams,
  PhoneNumverGetPhoneNumversParams,
  PhoneNumverPostPhoneNumvers200,
  PhoneNumverPostPhoneNumversBody,
  PhoneNumverPostPhoneNumversParams,
  PhoneNumverPutPhoneNumversById200,
  PhoneNumverPutPhoneNumversByIdBody,
  PhoneNumverPutPhoneNumversByIdParams,
} from "../learningStrapiV5.schemas";

import { strapiClient } from "../../../lib/strapi-client";

export const getPhoneNumver = () => {
  const phoneNumverGetPhoneNumvers = (
    params?: PhoneNumverGetPhoneNumversParams,
  ) => {
    return strapiClient<PhoneNumverGetPhoneNumvers200>({
      url: `/phone-numvers`,
      method: "GET",
      params,
    });
  };
  const phoneNumverPostPhoneNumvers = (
    phoneNumverPostPhoneNumversBody: PhoneNumverPostPhoneNumversBody,
    params?: PhoneNumverPostPhoneNumversParams,
  ) => {
    return strapiClient<PhoneNumverPostPhoneNumvers200>({
      url: `/phone-numvers`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: phoneNumverPostPhoneNumversBody,
      params,
    });
  };
  const phoneNumverGetPhoneNumversById = (
    id: string,
    params?: PhoneNumverGetPhoneNumversByIdParams,
  ) => {
    return strapiClient<PhoneNumverGetPhoneNumversById200>({
      url: `/phone-numvers/${id}`,
      method: "GET",
      params,
    });
  };
  const phoneNumverPutPhoneNumversById = (
    id: string,
    phoneNumverPutPhoneNumversByIdBody: PhoneNumverPutPhoneNumversByIdBody,
    params?: PhoneNumverPutPhoneNumversByIdParams,
  ) => {
    return strapiClient<PhoneNumverPutPhoneNumversById200>({
      url: `/phone-numvers/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: phoneNumverPutPhoneNumversByIdBody,
      params,
    });
  };
  const phoneNumverDeletePhoneNumversById = (
    id: string,
    params?: PhoneNumverDeletePhoneNumversByIdParams,
  ) => {
    return strapiClient<PhoneNumverDeletePhoneNumversById200>({
      url: `/phone-numvers/${id}`,
      method: "DELETE",
      params,
    });
  };
  return {
    phoneNumverGetPhoneNumvers,
    phoneNumverPostPhoneNumvers,
    phoneNumverGetPhoneNumversById,
    phoneNumverPutPhoneNumversById,
    phoneNumverDeletePhoneNumversById,
  };
};
export type PhoneNumverGetPhoneNumversResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPhoneNumver>["phoneNumverGetPhoneNumvers"]>
  >
>;
export type PhoneNumverPostPhoneNumversResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPhoneNumver>["phoneNumverPostPhoneNumvers"]>
  >
>;
export type PhoneNumverGetPhoneNumversByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPhoneNumver>["phoneNumverGetPhoneNumversById"]
    >
  >
>;
export type PhoneNumverPutPhoneNumversByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPhoneNumver>["phoneNumverPutPhoneNumversById"]
    >
  >
>;
export type PhoneNumverDeletePhoneNumversByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPhoneNumver>["phoneNumverDeletePhoneNumversById"]
    >
  >
>;
