/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  IngredientDeleteIngredientsById200,
  IngredientDeleteIngredientsByIdParams,
  IngredientGetIngredients200,
  IngredientGetIngredientsById200,
  IngredientGetIngredientsByIdParams,
  IngredientGetIngredientsParams,
  IngredientPostIngredients200,
  IngredientPostIngredientsBody,
  IngredientPostIngredientsParams,
  IngredientPutIngredientsById200,
  IngredientPutIngredientsByIdBody,
  IngredientPutIngredientsByIdParams,
} from "../learningStrapiV5.schemas";

import { strapiAuthenticatedClient } from "../../lib/strapi-client";

export const getIngredient = () => {
  const ingredientGetIngredients = (
    params?: IngredientGetIngredientsParams,
  ) => {
    return strapiAuthenticatedClient<IngredientGetIngredients200>({
      url: `/ingredients`,
      method: "GET",
      params,
    });
  };
  const ingredientPostIngredients = (
    ingredientPostIngredientsBody: IngredientPostIngredientsBody,
    params?: IngredientPostIngredientsParams,
  ) => {
    return strapiAuthenticatedClient<IngredientPostIngredients200>({
      url: `/ingredients`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: ingredientPostIngredientsBody,
      params,
    });
  };
  const ingredientGetIngredientsById = (
    id: string,
    params?: IngredientGetIngredientsByIdParams,
  ) => {
    return strapiAuthenticatedClient<IngredientGetIngredientsById200>({
      url: `/ingredients/${id}`,
      method: "GET",
      params,
    });
  };
  const ingredientPutIngredientsById = (
    id: string,
    ingredientPutIngredientsByIdBody: IngredientPutIngredientsByIdBody,
    params?: IngredientPutIngredientsByIdParams,
  ) => {
    return strapiAuthenticatedClient<IngredientPutIngredientsById200>({
      url: `/ingredients/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: ingredientPutIngredientsByIdBody,
      params,
    });
  };
  const ingredientDeleteIngredientsById = (
    id: string,
    params?: IngredientDeleteIngredientsByIdParams,
  ) => {
    return strapiAuthenticatedClient<IngredientDeleteIngredientsById200>({
      url: `/ingredients/${id}`,
      method: "DELETE",
      params,
    });
  };
  return {
    ingredientGetIngredients,
    ingredientPostIngredients,
    ingredientGetIngredientsById,
    ingredientPutIngredientsById,
    ingredientDeleteIngredientsById,
  };
};
export type IngredientGetIngredientsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getIngredient>["ingredientGetIngredients"]>
  >
>;
export type IngredientPostIngredientsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getIngredient>["ingredientPostIngredients"]>
  >
>;
export type IngredientGetIngredientsByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getIngredient>["ingredientGetIngredientsById"]>
  >
>;
export type IngredientPutIngredientsByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getIngredient>["ingredientPutIngredientsById"]>
  >
>;
export type IngredientDeleteIngredientsByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIngredient>["ingredientDeleteIngredientsById"]
    >
  >
>;
