/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  CategoryDeleteCategoriesById200,
  CategoryDeleteCategoriesByIdParams,
  CategoryGetCategories200,
  CategoryGetCategoriesById200,
  CategoryGetCategoriesByIdParams,
  CategoryGetCategoriesParams,
  CategoryPostCategories200,
  CategoryPostCategoriesBody,
  CategoryPostCategoriesParams,
  CategoryPutCategoriesById200,
  CategoryPutCategoriesByIdBody,
  CategoryPutCategoriesByIdParams,
} from "../learningStrapiV5.schemas";

import { strapiAuthenticatedClient } from "../../lib/strapi-client";

export const getCategory = () => {
  const categoryGetCategories = (params?: CategoryGetCategoriesParams) => {
    return strapiAuthenticatedClient<CategoryGetCategories200>({
      url: `/categories`,
      method: "GET",
      params,
    });
  };
  const categoryPostCategories = (
    categoryPostCategoriesBody: CategoryPostCategoriesBody,
    params?: CategoryPostCategoriesParams,
  ) => {
    return strapiAuthenticatedClient<CategoryPostCategories200>({
      url: `/categories`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: categoryPostCategoriesBody,
      params,
    });
  };
  const categoryGetCategoriesById = (
    id: string,
    params?: CategoryGetCategoriesByIdParams,
  ) => {
    return strapiAuthenticatedClient<CategoryGetCategoriesById200>({
      url: `/categories/${id}`,
      method: "GET",
      params,
    });
  };
  const categoryPutCategoriesById = (
    id: string,
    categoryPutCategoriesByIdBody: CategoryPutCategoriesByIdBody,
    params?: CategoryPutCategoriesByIdParams,
  ) => {
    return strapiAuthenticatedClient<CategoryPutCategoriesById200>({
      url: `/categories/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: categoryPutCategoriesByIdBody,
      params,
    });
  };
  const categoryDeleteCategoriesById = (
    id: string,
    params?: CategoryDeleteCategoriesByIdParams,
  ) => {
    return strapiAuthenticatedClient<CategoryDeleteCategoriesById200>({
      url: `/categories/${id}`,
      method: "DELETE",
      params,
    });
  };
  return {
    categoryGetCategories,
    categoryPostCategories,
    categoryGetCategoriesById,
    categoryPutCategoriesById,
    categoryDeleteCategoriesById,
  };
};
export type CategoryGetCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategory>["categoryGetCategories"]>>
>;
export type CategoryPostCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCategory>["categoryPostCategories"]>>
>;
export type CategoryGetCategoriesByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCategory>["categoryGetCategoriesById"]>
  >
>;
export type CategoryPutCategoriesByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCategory>["categoryPutCategoriesById"]>
  >
>;
export type CategoryDeleteCategoriesByIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCategory>["categoryDeleteCategoriesById"]>
  >
>;
