/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  RecipeDeleteRecipesById200,
  RecipeDeleteRecipesByIdParams,
  RecipeGetRecipes200,
  RecipeGetRecipesById200,
  RecipeGetRecipesByIdParams,
  RecipeGetRecipesParams,
  RecipePostRecipes200,
  RecipePostRecipesBody,
  RecipePostRecipesParams,
  RecipePutRecipesById200,
  RecipePutRecipesByIdBody,
  RecipePutRecipesByIdParams,
} from "../learningStrapiV5.schemas";

import { strapiAuthenticatedClient } from "../../lib/strapi-client";

export const getRecipe = () => {
  const recipeGetRecipes = (params?: RecipeGetRecipesParams) => {
    return strapiAuthenticatedClient<RecipeGetRecipes200>({
      url: `/recipes`,
      method: "GET",
      params,
    });
  };
  const recipePostRecipes = (
    recipePostRecipesBody: RecipePostRecipesBody,
    params?: RecipePostRecipesParams,
  ) => {
    return strapiAuthenticatedClient<RecipePostRecipes200>({
      url: `/recipes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: recipePostRecipesBody,
      params,
    });
  };
  const recipeGetRecipesById = (
    id: string,
    params?: RecipeGetRecipesByIdParams,
  ) => {
    return strapiAuthenticatedClient<RecipeGetRecipesById200>({
      url: `/recipes/${id}`,
      method: "GET",
      params,
    });
  };
  const recipePutRecipesById = (
    id: string,
    recipePutRecipesByIdBody: RecipePutRecipesByIdBody,
    params?: RecipePutRecipesByIdParams,
  ) => {
    return strapiAuthenticatedClient<RecipePutRecipesById200>({
      url: `/recipes/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: recipePutRecipesByIdBody,
      params,
    });
  };
  const recipeDeleteRecipesById = (
    id: string,
    params?: RecipeDeleteRecipesByIdParams,
  ) => {
    return strapiAuthenticatedClient<RecipeDeleteRecipesById200>({
      url: `/recipes/${id}`,
      method: "DELETE",
      params,
    });
  };
  return {
    recipeGetRecipes,
    recipePostRecipes,
    recipeGetRecipesById,
    recipePutRecipesById,
    recipeDeleteRecipesById,
  };
};
export type RecipeGetRecipesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipe>["recipeGetRecipes"]>>
>;
export type RecipePostRecipesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipe>["recipePostRecipes"]>>
>;
export type RecipeGetRecipesByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipe>["recipeGetRecipesById"]>>
>;
export type RecipePutRecipesByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipe>["recipePutRecipesById"]>>
>;
export type RecipeDeleteRecipesByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRecipe>["recipeDeleteRecipesById"]>>
>;
