/**
 * Generated by orval v7.16.0
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const phoneNumverGetPhoneNumversQueryPaginationPageMax = 9007199254740991;

export const phoneNumverGetPhoneNumversQueryPaginationPageSizeMax = 9007199254740991;

export const phoneNumverGetPhoneNumversQueryPaginationStartMin = 0;
export const phoneNumverGetPhoneNumversQueryPaginationStartMax = 9007199254740991;

export const phoneNumverGetPhoneNumversQueryPaginationLimitMax = 9007199254740991;

export const phoneNumverGetPhoneNumversQueryParams = zod.object({
  fields: zod
    .array(zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]))
    .optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
  _q: zod.string().optional(),
  pagination: zod
    .object({
      withCount: zod
        .boolean()
        .optional()
        .describe("Include total count in response"),
    })
    .and(
      zod.union([
        zod
          .object({
            page: zod
              .number()
              .max(phoneNumverGetPhoneNumversQueryPaginationPageMax)
              .describe("Page number (1-based)"),
            pageSize: zod
              .number()
              .max(phoneNumverGetPhoneNumversQueryPaginationPageSizeMax)
              .describe("Number of entries per page"),
          })
          .describe("Page-based pagination"),
        zod
          .object({
            start: zod
              .number()
              .min(phoneNumverGetPhoneNumversQueryPaginationStartMin)
              .max(phoneNumverGetPhoneNumversQueryPaginationStartMax)
              .describe("Number of entries to skip"),
            limit: zod
              .number()
              .max(phoneNumverGetPhoneNumversQueryPaginationLimitMax)
              .describe("Maximum number of entries to return"),
          })
          .describe("Offset-based pagination"),
      ]),
    )
    .optional(),
  sort: zod
    .union([
      zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]),
      zod.array(
        zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]),
      ),
      zod.record(zod.string(), zod.enum(["asc", "desc"])),
      zod.array(zod.record(zod.string(), zod.enum(["asc", "desc"]))),
    ])
    .optional(),
  populate: zod
    .union([
      zod
        .literal("*")
        .describe(
          "Populate all the first level relations, components, files, and dynamic zones for the entry",
        ),
      zod
        .enum(["user"])
        .describe(
          "Populate a single relation, component, file, or dynamic zone",
        ),
      zod
        .array(zod.enum(["user"]))
        .describe(
          "Populate a selection of multiple relations, components, files, or dynamic zones",
        ),
    ])
    .optional(),
});

export const phoneNumverGetPhoneNumversResponseDataItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversResponseDataItemDumbNumberMin =
  -9007199254740991;
export const phoneNumverGetPhoneNumversResponseDataItemDumbNumberMax = 9007199254740991;

export const phoneNumverGetPhoneNumversResponseDataItemUserDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversResponseDataItemUserEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );
export const phoneNumverGetPhoneNumversResponseDataItemUserConfirmedDefault = false;
export const phoneNumverGetPhoneNumversResponseDataItemUserBlockedDefault = false;
export const phoneNumverGetPhoneNumversResponseDataItemUserIsPhoneVerifiedDefault = false;
export const phoneNumverGetPhoneNumversResponseDataItemUserRoleDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversResponseDataItemUserRolePermissionsItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );

export const phoneNumverGetPhoneNumversResponse = zod.object({
  data: zod.array(
    zod
      .object({
        documentId: zod
          .uuid()
          .regex(phoneNumverGetPhoneNumversResponseDataItemDocumentIdRegExp)
          .describe("The document ID, represented by a UUID"),
        id: zod.union([zod.string(), zod.number()]),
        dumb_number: zod
          .number()
          .min(phoneNumverGetPhoneNumversResponseDataItemDumbNumberMin)
          .max(phoneNumverGetPhoneNumversResponseDataItemDumbNumberMax)
          .optional()
          .describe("An integer field"),
        createdAt: zod.iso.datetime({}).optional().describe("A datetime field"),
        updatedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
        publishedAt: zod.iso.datetime({}).describe("A datetime field"),
        user: zod
          .object({
            documentId: zod
              .uuid()
              .regex(
                phoneNumverGetPhoneNumversResponseDataItemUserDocumentIdRegExp,
              )
              .describe("Unique document identifier (UUID v4)"),
            id: zod.union([zod.string(), zod.number()]),
            username: zod
              .string()
              .describe("User's unique username for authentication"),
            email: zod
              .email()
              .regex(phoneNumverGetPhoneNumversResponseDataItemUserEmailRegExp)
              .describe("User's email address (unique, validated)"),
            provider: zod.string().optional().describe("A string field"),
            confirmed: zod
              .union([zod.boolean(), zod.null()])
              .describe("Whether email has been confirmed"),
            blocked: zod
              .union([zod.boolean(), zod.null()])
              .describe("Whether user is blocked from accessing the system"),
            isPhoneVerified: zod
              .union([zod.boolean(), zod.null()])
              .describe("Whether phone number has been verified"),
            createdAt: zod.iso
              .datetime({})
              .optional()
              .describe("A datetime field"),
            updatedAt: zod.iso
              .datetime({})
              .optional()
              .describe("A datetime field"),
            publishedAt: zod.iso.datetime({}).describe("A datetime field"),
            role: zod
              .object({
                documentId: zod
                  .uuid()
                  .regex(
                    phoneNumverGetPhoneNumversResponseDataItemUserRoleDocumentIdRegExp,
                  )
                  .describe("The document ID, represented by a UUID"),
                id: zod.union([zod.string(), zod.number()]),
                name: zod.string().describe("A string field"),
                description: zod.string().optional().describe("A string field"),
                type: zod.string().optional().describe("A string field"),
                createdAt: zod.iso
                  .datetime({})
                  .optional()
                  .describe("A datetime field"),
                updatedAt: zod.iso
                  .datetime({})
                  .optional()
                  .describe("A datetime field"),
                publishedAt: zod.iso.datetime({}).describe("A datetime field"),
                permissions: zod
                  .array(
                    zod.object({
                      documentId: zod
                        .uuid()
                        .regex(
                          phoneNumverGetPhoneNumversResponseDataItemUserRolePermissionsItemDocumentIdRegExp,
                        )
                        .describe("The document ID, represented by a UUID"),
                      id: zod.union([zod.string(), zod.number()]),
                      action: zod.string().describe("A string field"),
                      createdAt: zod.iso
                        .datetime({})
                        .optional()
                        .describe("A datetime field"),
                      updatedAt: zod.iso
                        .datetime({})
                        .optional()
                        .describe("A datetime field"),
                      publishedAt: zod.iso
                        .datetime({})
                        .describe("A datetime field"),
                      role: zod.unknown().optional(),
                    }),
                  )
                  .optional()
                  .describe("A relational field"),
                users: zod
                  .array(zod.unknown())
                  .optional()
                  .describe("A relational field"),
              })
              .optional(),
            phone_numvers: zod
              .array(zod.unknown())
              .optional()
              .describe("A relational field"),
          })
          .optional()
          .describe(
            "User document with authentication and profile information",
          ),
      })
      .describe("Phone number entity"),
  ),
});

export const phoneNumverPostPhoneNumversQueryParams = zod.object({
  fields: zod
    .array(zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]))
    .optional(),
  populate: zod
    .union([
      zod
        .literal("*")
        .describe(
          "Populate all the first level relations, components, files, and dynamic zones for the entry",
        ),
      zod
        .enum(["user"])
        .describe(
          "Populate a single relation, component, file, or dynamic zone",
        ),
      zod
        .array(zod.enum(["user"]))
        .describe(
          "Populate a selection of multiple relations, components, files, or dynamic zones",
        ),
    ])
    .optional(),
});

export const phoneNumverPostPhoneNumversBodyDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverPostPhoneNumversBodyDataDumbNumberMax = 9007199254740991;

export const phoneNumverPostPhoneNumversBodyDataUserRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);

export const phoneNumverPostPhoneNumversBody = zod.object({
  data: zod.object({
    dumb_number: zod
      .number()
      .min(phoneNumverPostPhoneNumversBodyDataDumbNumberMin)
      .max(phoneNumverPostPhoneNumversBodyDataDumbNumberMax)
      .optional()
      .describe("A float field"),
    publishedAt: zod.iso.datetime({}).describe("A datetime field"),
    user: zod
      .uuid()
      .regex(phoneNumverPostPhoneNumversBodyDataUserRegExp)
      .optional()
      .describe("A relational field"),
  }),
});

export const phoneNumverPostPhoneNumversResponseDataDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPostPhoneNumversResponseDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverPostPhoneNumversResponseDataDumbNumberMax = 9007199254740991;

export const phoneNumverPostPhoneNumversResponseDataUserDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPostPhoneNumversResponseDataUserEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );
export const phoneNumverPostPhoneNumversResponseDataUserConfirmedDefault = false;
export const phoneNumverPostPhoneNumversResponseDataUserBlockedDefault = false;
export const phoneNumverPostPhoneNumversResponseDataUserIsPhoneVerifiedDefault = false;
export const phoneNumverPostPhoneNumversResponseDataUserRoleDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPostPhoneNumversResponseDataUserRolePermissionsItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );

export const phoneNumverPostPhoneNumversResponse = zod.object({
  data: zod
    .object({
      documentId: zod
        .uuid()
        .regex(phoneNumverPostPhoneNumversResponseDataDocumentIdRegExp)
        .describe("The document ID, represented by a UUID"),
      id: zod.union([zod.string(), zod.number()]),
      dumb_number: zod
        .number()
        .min(phoneNumverPostPhoneNumversResponseDataDumbNumberMin)
        .max(phoneNumverPostPhoneNumversResponseDataDumbNumberMax)
        .optional()
        .describe("An integer field"),
      createdAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      updatedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      publishedAt: zod.iso.datetime({}).describe("A datetime field"),
      user: zod
        .object({
          documentId: zod
            .uuid()
            .regex(phoneNumverPostPhoneNumversResponseDataUserDocumentIdRegExp)
            .describe("Unique document identifier (UUID v4)"),
          id: zod.union([zod.string(), zod.number()]),
          username: zod
            .string()
            .describe("User's unique username for authentication"),
          email: zod
            .email()
            .regex(phoneNumverPostPhoneNumversResponseDataUserEmailRegExp)
            .describe("User's email address (unique, validated)"),
          provider: zod.string().optional().describe("A string field"),
          confirmed: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether email has been confirmed"),
          blocked: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether user is blocked from accessing the system"),
          isPhoneVerified: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether phone number has been verified"),
          createdAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          updatedAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          publishedAt: zod.iso.datetime({}).describe("A datetime field"),
          role: zod
            .object({
              documentId: zod
                .uuid()
                .regex(
                  phoneNumverPostPhoneNumversResponseDataUserRoleDocumentIdRegExp,
                )
                .describe("The document ID, represented by a UUID"),
              id: zod.union([zod.string(), zod.number()]),
              name: zod.string().describe("A string field"),
              description: zod.string().optional().describe("A string field"),
              type: zod.string().optional().describe("A string field"),
              createdAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              updatedAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              publishedAt: zod.iso.datetime({}).describe("A datetime field"),
              permissions: zod
                .array(
                  zod.object({
                    documentId: zod
                      .uuid()
                      .regex(
                        phoneNumverPostPhoneNumversResponseDataUserRolePermissionsItemDocumentIdRegExp,
                      )
                      .describe("The document ID, represented by a UUID"),
                    id: zod.union([zod.string(), zod.number()]),
                    action: zod.string().describe("A string field"),
                    createdAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    updatedAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    publishedAt: zod.iso
                      .datetime({})
                      .describe("A datetime field"),
                    role: zod.unknown().optional(),
                  }),
                )
                .optional()
                .describe("A relational field"),
              users: zod
                .array(zod.unknown())
                .optional()
                .describe("A relational field"),
            })
            .optional(),
          phone_numvers: zod
            .array(zod.unknown())
            .optional()
            .describe("A relational field"),
        })
        .optional()
        .describe("User document with authentication and profile information"),
    })
    .describe("Phone number entity"),
});

export const phoneNumverGetPhoneNumversByIdPathIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);

export const phoneNumverGetPhoneNumversByIdParams = zod.object({
  id: zod.uuid().regex(phoneNumverGetPhoneNumversByIdPathIdRegExp),
});

export const phoneNumverGetPhoneNumversByIdQueryParams = zod.object({
  fields: zod
    .array(zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]))
    .optional(),
  populate: zod
    .union([
      zod
        .literal("*")
        .describe(
          "Populate all the first level relations, components, files, and dynamic zones for the entry",
        ),
      zod
        .enum(["user"])
        .describe(
          "Populate a single relation, component, file, or dynamic zone",
        ),
      zod
        .array(zod.enum(["user"]))
        .describe(
          "Populate a selection of multiple relations, components, files, or dynamic zones",
        ),
    ])
    .optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
  sort: zod
    .union([
      zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]),
      zod.array(
        zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]),
      ),
      zod.record(zod.string(), zod.enum(["asc", "desc"])),
      zod.array(zod.record(zod.string(), zod.enum(["asc", "desc"]))),
    ])
    .optional(),
});

export const phoneNumverGetPhoneNumversByIdResponseDataDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversByIdResponseDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverGetPhoneNumversByIdResponseDataDumbNumberMax = 9007199254740991;

export const phoneNumverGetPhoneNumversByIdResponseDataUserDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversByIdResponseDataUserEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );
export const phoneNumverGetPhoneNumversByIdResponseDataUserConfirmedDefault = false;
export const phoneNumverGetPhoneNumversByIdResponseDataUserBlockedDefault = false;
export const phoneNumverGetPhoneNumversByIdResponseDataUserIsPhoneVerifiedDefault = false;
export const phoneNumverGetPhoneNumversByIdResponseDataUserRoleDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverGetPhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );

export const phoneNumverGetPhoneNumversByIdResponse = zod.object({
  data: zod
    .object({
      documentId: zod
        .uuid()
        .regex(phoneNumverGetPhoneNumversByIdResponseDataDocumentIdRegExp)
        .describe("The document ID, represented by a UUID"),
      id: zod.union([zod.string(), zod.number()]),
      dumb_number: zod
        .number()
        .min(phoneNumverGetPhoneNumversByIdResponseDataDumbNumberMin)
        .max(phoneNumverGetPhoneNumversByIdResponseDataDumbNumberMax)
        .optional()
        .describe("An integer field"),
      createdAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      updatedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      publishedAt: zod.iso.datetime({}).describe("A datetime field"),
      user: zod
        .object({
          documentId: zod
            .uuid()
            .regex(
              phoneNumverGetPhoneNumversByIdResponseDataUserDocumentIdRegExp,
            )
            .describe("Unique document identifier (UUID v4)"),
          id: zod.union([zod.string(), zod.number()]),
          username: zod
            .string()
            .describe("User's unique username for authentication"),
          email: zod
            .email()
            .regex(phoneNumverGetPhoneNumversByIdResponseDataUserEmailRegExp)
            .describe("User's email address (unique, validated)"),
          provider: zod.string().optional().describe("A string field"),
          confirmed: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether email has been confirmed"),
          blocked: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether user is blocked from accessing the system"),
          isPhoneVerified: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether phone number has been verified"),
          createdAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          updatedAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          publishedAt: zod.iso.datetime({}).describe("A datetime field"),
          role: zod
            .object({
              documentId: zod
                .uuid()
                .regex(
                  phoneNumverGetPhoneNumversByIdResponseDataUserRoleDocumentIdRegExp,
                )
                .describe("The document ID, represented by a UUID"),
              id: zod.union([zod.string(), zod.number()]),
              name: zod.string().describe("A string field"),
              description: zod.string().optional().describe("A string field"),
              type: zod.string().optional().describe("A string field"),
              createdAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              updatedAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              publishedAt: zod.iso.datetime({}).describe("A datetime field"),
              permissions: zod
                .array(
                  zod.object({
                    documentId: zod
                      .uuid()
                      .regex(
                        phoneNumverGetPhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp,
                      )
                      .describe("The document ID, represented by a UUID"),
                    id: zod.union([zod.string(), zod.number()]),
                    action: zod.string().describe("A string field"),
                    createdAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    updatedAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    publishedAt: zod.iso
                      .datetime({})
                      .describe("A datetime field"),
                    role: zod.unknown().optional(),
                  }),
                )
                .optional()
                .describe("A relational field"),
              users: zod
                .array(zod.unknown())
                .optional()
                .describe("A relational field"),
            })
            .optional(),
          phone_numvers: zod
            .array(zod.unknown())
            .optional()
            .describe("A relational field"),
        })
        .optional()
        .describe("User document with authentication and profile information"),
    })
    .describe("Phone number entity"),
});

export const phoneNumverPutPhoneNumversByIdPathIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);

export const phoneNumverPutPhoneNumversByIdParams = zod.object({
  id: zod.uuid().regex(phoneNumverPutPhoneNumversByIdPathIdRegExp),
});

export const phoneNumverPutPhoneNumversByIdQueryParams = zod.object({
  fields: zod
    .array(zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]))
    .optional(),
  populate: zod
    .union([
      zod
        .literal("*")
        .describe(
          "Populate all the first level relations, components, files, and dynamic zones for the entry",
        ),
      zod
        .enum(["user"])
        .describe(
          "Populate a single relation, component, file, or dynamic zone",
        ),
      zod
        .array(zod.enum(["user"]))
        .describe(
          "Populate a selection of multiple relations, components, files, or dynamic zones",
        ),
    ])
    .optional(),
});

export const phoneNumverPutPhoneNumversByIdBodyDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverPutPhoneNumversByIdBodyDataDumbNumberMax = 9007199254740991;

export const phoneNumverPutPhoneNumversByIdBodyDataUserRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);

export const phoneNumverPutPhoneNumversByIdBody = zod.object({
  data: zod.object({
    dumb_number: zod
      .number()
      .min(phoneNumverPutPhoneNumversByIdBodyDataDumbNumberMin)
      .max(phoneNumverPutPhoneNumversByIdBodyDataDumbNumberMax)
      .optional()
      .describe("A float field"),
    publishedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
    user: zod
      .uuid()
      .regex(phoneNumverPutPhoneNumversByIdBodyDataUserRegExp)
      .optional()
      .describe("A relational field"),
  }),
});

export const phoneNumverPutPhoneNumversByIdResponseDataDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPutPhoneNumversByIdResponseDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverPutPhoneNumversByIdResponseDataDumbNumberMax = 9007199254740991;

export const phoneNumverPutPhoneNumversByIdResponseDataUserDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPutPhoneNumversByIdResponseDataUserEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );
export const phoneNumverPutPhoneNumversByIdResponseDataUserConfirmedDefault = false;
export const phoneNumverPutPhoneNumversByIdResponseDataUserBlockedDefault = false;
export const phoneNumverPutPhoneNumversByIdResponseDataUserIsPhoneVerifiedDefault = false;
export const phoneNumverPutPhoneNumversByIdResponseDataUserRoleDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverPutPhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );

export const phoneNumverPutPhoneNumversByIdResponse = zod.object({
  data: zod
    .object({
      documentId: zod
        .uuid()
        .regex(phoneNumverPutPhoneNumversByIdResponseDataDocumentIdRegExp)
        .describe("The document ID, represented by a UUID"),
      id: zod.union([zod.string(), zod.number()]),
      dumb_number: zod
        .number()
        .min(phoneNumverPutPhoneNumversByIdResponseDataDumbNumberMin)
        .max(phoneNumverPutPhoneNumversByIdResponseDataDumbNumberMax)
        .optional()
        .describe("An integer field"),
      createdAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      updatedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      publishedAt: zod.iso.datetime({}).describe("A datetime field"),
      user: zod
        .object({
          documentId: zod
            .uuid()
            .regex(
              phoneNumverPutPhoneNumversByIdResponseDataUserDocumentIdRegExp,
            )
            .describe("Unique document identifier (UUID v4)"),
          id: zod.union([zod.string(), zod.number()]),
          username: zod
            .string()
            .describe("User's unique username for authentication"),
          email: zod
            .email()
            .regex(phoneNumverPutPhoneNumversByIdResponseDataUserEmailRegExp)
            .describe("User's email address (unique, validated)"),
          provider: zod.string().optional().describe("A string field"),
          confirmed: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether email has been confirmed"),
          blocked: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether user is blocked from accessing the system"),
          isPhoneVerified: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether phone number has been verified"),
          createdAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          updatedAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          publishedAt: zod.iso.datetime({}).describe("A datetime field"),
          role: zod
            .object({
              documentId: zod
                .uuid()
                .regex(
                  phoneNumverPutPhoneNumversByIdResponseDataUserRoleDocumentIdRegExp,
                )
                .describe("The document ID, represented by a UUID"),
              id: zod.union([zod.string(), zod.number()]),
              name: zod.string().describe("A string field"),
              description: zod.string().optional().describe("A string field"),
              type: zod.string().optional().describe("A string field"),
              createdAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              updatedAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              publishedAt: zod.iso.datetime({}).describe("A datetime field"),
              permissions: zod
                .array(
                  zod.object({
                    documentId: zod
                      .uuid()
                      .regex(
                        phoneNumverPutPhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp,
                      )
                      .describe("The document ID, represented by a UUID"),
                    id: zod.union([zod.string(), zod.number()]),
                    action: zod.string().describe("A string field"),
                    createdAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    updatedAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    publishedAt: zod.iso
                      .datetime({})
                      .describe("A datetime field"),
                    role: zod.unknown().optional(),
                  }),
                )
                .optional()
                .describe("A relational field"),
              users: zod
                .array(zod.unknown())
                .optional()
                .describe("A relational field"),
            })
            .optional(),
          phone_numvers: zod
            .array(zod.unknown())
            .optional()
            .describe("A relational field"),
        })
        .optional()
        .describe("User document with authentication and profile information"),
    })
    .describe("Phone number entity"),
});

export const phoneNumverDeletePhoneNumversByIdPathIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);

export const phoneNumverDeletePhoneNumversByIdParams = zod.object({
  id: zod.uuid().regex(phoneNumverDeletePhoneNumversByIdPathIdRegExp),
});

export const phoneNumverDeletePhoneNumversByIdQueryParams = zod.object({
  fields: zod
    .array(zod.enum(["dumb_number", "createdAt", "updatedAt", "publishedAt"]))
    .optional(),
  populate: zod
    .union([
      zod
        .literal("*")
        .describe(
          "Populate all the first level relations, components, files, and dynamic zones for the entry",
        ),
      zod
        .enum(["user"])
        .describe(
          "Populate a single relation, component, file, or dynamic zone",
        ),
      zod
        .array(zod.enum(["user"]))
        .describe(
          "Populate a selection of multiple relations, components, files, or dynamic zones",
        ),
    ])
    .optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
});

export const phoneNumverDeletePhoneNumversByIdResponseDataDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverDeletePhoneNumversByIdResponseDataDumbNumberMin =
  -9007199254740991;
export const phoneNumverDeletePhoneNumversByIdResponseDataDumbNumberMax = 9007199254740991;

export const phoneNumverDeletePhoneNumversByIdResponseDataUserDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverDeletePhoneNumversByIdResponseDataUserEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );
export const phoneNumverDeletePhoneNumversByIdResponseDataUserConfirmedDefault = false;
export const phoneNumverDeletePhoneNumversByIdResponseDataUserBlockedDefault = false;
export const phoneNumverDeletePhoneNumversByIdResponseDataUserIsPhoneVerifiedDefault = false;
export const phoneNumverDeletePhoneNumversByIdResponseDataUserRoleDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );
export const phoneNumverDeletePhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp =
  new RegExp(
    "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
  );

export const phoneNumverDeletePhoneNumversByIdResponse = zod.object({
  data: zod
    .object({
      documentId: zod
        .uuid()
        .regex(phoneNumverDeletePhoneNumversByIdResponseDataDocumentIdRegExp)
        .describe("The document ID, represented by a UUID"),
      id: zod.union([zod.string(), zod.number()]),
      dumb_number: zod
        .number()
        .min(phoneNumverDeletePhoneNumversByIdResponseDataDumbNumberMin)
        .max(phoneNumverDeletePhoneNumversByIdResponseDataDumbNumberMax)
        .optional()
        .describe("An integer field"),
      createdAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      updatedAt: zod.iso.datetime({}).optional().describe("A datetime field"),
      publishedAt: zod.iso.datetime({}).describe("A datetime field"),
      user: zod
        .object({
          documentId: zod
            .uuid()
            .regex(
              phoneNumverDeletePhoneNumversByIdResponseDataUserDocumentIdRegExp,
            )
            .describe("Unique document identifier (UUID v4)"),
          id: zod.union([zod.string(), zod.number()]),
          username: zod
            .string()
            .describe("User's unique username for authentication"),
          email: zod
            .email()
            .regex(phoneNumverDeletePhoneNumversByIdResponseDataUserEmailRegExp)
            .describe("User's email address (unique, validated)"),
          provider: zod.string().optional().describe("A string field"),
          confirmed: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether email has been confirmed"),
          blocked: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether user is blocked from accessing the system"),
          isPhoneVerified: zod
            .union([zod.boolean(), zod.null()])
            .describe("Whether phone number has been verified"),
          createdAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          updatedAt: zod.iso
            .datetime({})
            .optional()
            .describe("A datetime field"),
          publishedAt: zod.iso.datetime({}).describe("A datetime field"),
          role: zod
            .object({
              documentId: zod
                .uuid()
                .regex(
                  phoneNumverDeletePhoneNumversByIdResponseDataUserRoleDocumentIdRegExp,
                )
                .describe("The document ID, represented by a UUID"),
              id: zod.union([zod.string(), zod.number()]),
              name: zod.string().describe("A string field"),
              description: zod.string().optional().describe("A string field"),
              type: zod.string().optional().describe("A string field"),
              createdAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              updatedAt: zod.iso
                .datetime({})
                .optional()
                .describe("A datetime field"),
              publishedAt: zod.iso.datetime({}).describe("A datetime field"),
              permissions: zod
                .array(
                  zod.object({
                    documentId: zod
                      .uuid()
                      .regex(
                        phoneNumverDeletePhoneNumversByIdResponseDataUserRolePermissionsItemDocumentIdRegExp,
                      )
                      .describe("The document ID, represented by a UUID"),
                    id: zod.union([zod.string(), zod.number()]),
                    action: zod.string().describe("A string field"),
                    createdAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    updatedAt: zod.iso
                      .datetime({})
                      .optional()
                      .describe("A datetime field"),
                    publishedAt: zod.iso
                      .datetime({})
                      .describe("A datetime field"),
                    role: zod.unknown().optional(),
                  }),
                )
                .optional()
                .describe("A relational field"),
              users: zod
                .array(zod.unknown())
                .optional()
                .describe("A relational field"),
            })
            .optional(),
          phone_numvers: zod
            .array(zod.unknown())
            .optional()
            .describe("A relational field"),
        })
        .optional()
        .describe("User document with authentication and profile information"),
    })
    .describe("Phone number entity"),
});
