/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import { strapiAPITokenClient } from "../../lib/strapi-client";

export const getMcp = () => {
  const mcpGetStreamable = () => {
    return strapiAPITokenClient<unknown>({ url: `/streamable`, method: "GET" });
  };
  const mcpPostStreamable = () => {
    return strapiAPITokenClient<unknown>({
      url: `/streamable`,
      method: "POST",
    });
  };
  const mcpDeleteStreamable = () => {
    return strapiAPITokenClient<unknown>({
      url: `/streamable`,
      method: "DELETE",
    });
  };
  return { mcpGetStreamable, mcpPostStreamable, mcpDeleteStreamable };
};
export type McpGetStreamableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMcp>["mcpGetStreamable"]>>
>;
export type McpPostStreamableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMcp>["mcpPostStreamable"]>>
>;
export type McpDeleteStreamableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMcp>["mcpDeleteStreamable"]>>
>;
